### ISSUE TITLE
Custom extention for mondator

### ISSUE THREAD

**Issue by florynth** [mandango/MandangoBundle#8]
If we want to add extention to mondator we must create a service tag with 'mandango.mondator.extension' from what I understand in MandangoMondatorPass at line 57 but line 58 you are refering to 

$definition->addMethodCall

instead of

$mondatorDefinition->addMethodCall

P.s. : Sorry I'm pretty new at git I know I could probably do a pull request but I don't know how (yet)

**Comment by pablodip** [comment]
PR merged, thanks.
